// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package server

import (
	"context"

	"github.com/suiran17/go-zero-rag/aiservice/internal/logic"
	"github.com/suiran17/go-zero-rag/aiservice/internal/svc"
	"github.com/suiran17/go-zero-rag/aiservice/pb/pb"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

func (s *AiServer) Query(ctx context.Context, in *pb.QueryReq) (*pb.QueryResp, error) {
	l := logic.NewQueryLogic(ctx, s.svcCtx)
	return l.Query(in)
}
