// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: doc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadDocReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocReq) Reset() {
	*x = UploadDocReq{}
	mi := &file_doc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocReq) ProtoMessage() {}

func (x *UploadDocReq) ProtoReflect() protoreflect.Message {
	mi := &file_doc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocReq.ProtoReflect.Descriptor instead.
func (*UploadDocReq) Descriptor() ([]byte, []int) {
	return file_doc_proto_rawDescGZIP(), []int{0}
}

func (x *UploadDocReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadDocReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UploadDocResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocResp) Reset() {
	*x = UploadDocResp{}
	mi := &file_doc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocResp) ProtoMessage() {}

func (x *UploadDocResp) ProtoReflect() protoreflect.Message {
	mi := &file_doc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocResp.ProtoReflect.Descriptor instead.
func (*UploadDocResp) Descriptor() ([]byte, []int) {
	return file_doc_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocResp) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *UploadDocResp) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

var File_doc_proto protoreflect.FileDescriptor

const file_doc_proto_rawDesc = "" +
	"\n" +
	"\tdoc.proto\x12\x03doc\">\n" +
	"\fUploadDocReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"G\n" +
	"\rUploadDocResp\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x05R\n" +
	"chunkCount29\n" +
	"\x03Doc\x122\n" +
	"\tUploadDoc\x12\x11.doc.UploadDocReq\x1a\x12.doc.UploadDocRespB\x06Z\x04./pbb\x06proto3"

var (
	file_doc_proto_rawDescOnce sync.Once
	file_doc_proto_rawDescData []byte
)

func file_doc_proto_rawDescGZIP() []byte {
	file_doc_proto_rawDescOnce.Do(func() {
		file_doc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doc_proto_rawDesc), len(file_doc_proto_rawDesc)))
	})
	return file_doc_proto_rawDescData
}

var file_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_doc_proto_goTypes = []any{
	(*UploadDocReq)(nil),  // 0: doc.UploadDocReq
	(*UploadDocResp)(nil), // 1: doc.UploadDocResp
}
var file_doc_proto_depIdxs = []int32{
	0, // 0: doc.Doc.UploadDoc:input_type -> doc.UploadDocReq
	1, // 1: doc.Doc.UploadDoc:output_type -> doc.UploadDocResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doc_proto_init() }
func file_doc_proto_init() {
	if File_doc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doc_proto_rawDesc), len(file_doc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doc_proto_goTypes,
		DependencyIndexes: file_doc_proto_depIdxs,
		MessageInfos:      file_doc_proto_msgTypes,
	}.Build()
	File_doc_proto = out.File
	file_doc_proto_goTypes = nil
	file_doc_proto_depIdxs = nil
}
