// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: doc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Doc_UploadDoc_FullMethodName = "/doc.Doc/UploadDoc"
)

// DocClient is the client API for Doc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocClient interface {
	UploadDoc(ctx context.Context, in *UploadDocReq, opts ...grpc.CallOption) (*UploadDocResp, error)
}

type docClient struct {
	cc grpc.ClientConnInterface
}

func NewDocClient(cc grpc.ClientConnInterface) DocClient {
	return &docClient{cc}
}

func (c *docClient) UploadDoc(ctx context.Context, in *UploadDocReq, opts ...grpc.CallOption) (*UploadDocResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDocResp)
	err := c.cc.Invoke(ctx, Doc_UploadDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocServer is the server API for Doc service.
// All implementations must embed UnimplementedDocServer
// for forward compatibility.
type DocServer interface {
	UploadDoc(context.Context, *UploadDocReq) (*UploadDocResp, error)
	mustEmbedUnimplementedDocServer()
}

// UnimplementedDocServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocServer struct{}

func (UnimplementedDocServer) UploadDoc(context.Context, *UploadDocReq) (*UploadDocResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadDoc not implemented")
}
func (UnimplementedDocServer) mustEmbedUnimplementedDocServer() {}
func (UnimplementedDocServer) testEmbeddedByValue()             {}

// UnsafeDocServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocServer will
// result in compilation errors.
type UnsafeDocServer interface {
	mustEmbedUnimplementedDocServer()
}

func RegisterDocServer(s grpc.ServiceRegistrar, srv DocServer) {
	// If the following call pancis, it indicates UnimplementedDocServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Doc_ServiceDesc, srv)
}

func _Doc_UploadDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServer).UploadDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Doc_UploadDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServer).UploadDoc(ctx, req.(*UploadDocReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Doc_ServiceDesc is the grpc.ServiceDesc for Doc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Doc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doc.Doc",
	HandlerType: (*DocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadDoc",
			Handler:    _Doc_UploadDoc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doc.proto",
}
