// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/suiran17/go-zero-rag/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/doc/upload",
				Handler: UploadDocHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/qa/query",
				Handler: QueryHandler(serverCtx),
			},
		},
	)
}
