// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: doc.proto

package doc

import (
	"context"

	"github.com/suiran17/go-zero-rag/docservice/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UploadDocReq  = pb.UploadDocReq
	UploadDocResp = pb.UploadDocResp

	Doc interface {
		UploadDoc(ctx context.Context, in *UploadDocReq, opts ...grpc.CallOption) (*UploadDocResp, error)
	}

	defaultDoc struct {
		cli zrpc.Client
	}
)

func NewDoc(cli zrpc.Client) Doc {
	return &defaultDoc{
		cli: cli,
	}
}

func (m *defaultDoc) UploadDoc(ctx context.Context, in *UploadDocReq, opts ...grpc.CallOption) (*UploadDocResp, error) {
	client := pb.NewDocClient(m.cli.Conn())
	return client.UploadDoc(ctx, in, opts...)
}
