// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type QueryReq struct {
	Question string `json:"question"`
	TopK     int    `json:"top_k,optional,default=3"`
}

type QueryResp struct {
	Answer  string   `json:"answer"`
	Sources []string `json:"sources"`
}

type UploadDocReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UploadDocResp struct {
	DocId      string `json:"doc_id"`
	ChunkCount int    `json:"chunk_count"`
}
