// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: doc.proto

package server

import (
	"context"

	"github.com/suiran17/go-zero-rag/docservice/internal/logic"
	"github.com/suiran17/go-zero-rag/docservice/internal/svc"
	"github.com/suiran17/go-zero-rag/docservice/pb/pb"
)

type DocServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDocServer
}

func NewDocServer(svcCtx *svc.ServiceContext) *DocServer {
	return &DocServer{
		svcCtx: svcCtx,
	}
}

func (s *DocServer) UploadDoc(ctx context.Context, in *pb.UploadDocReq) (*pb.UploadDocResp, error) {
	l := logic.NewUploadDocLogic(ctx, s.svcCtx)
	return l.UploadDoc(in)
}
