// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package ai

import (
	"context"

	"github.com/suiran17/go-zero-rag/aiservice/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	QueryReq  = pb.QueryReq
	QueryResp = pb.QueryResp

	Ai interface {
		Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
	}

	defaultAi struct {
		cli zrpc.Client
	}
)

func NewAi(cli zrpc.Client) Ai {
	return &defaultAi{
		cli: cli,
	}
}

func (m *defaultAi) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	client := pb.NewAiClient(m.cli.Conn())
	return client.Query(ctx, in, opts...)
}
